<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2020/03/09 13:31:16

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:dbname=hnapttr;host=localhost;port=3308',
  'profiler' => false,
  'username' => 'root',
  'password' => '',
  'attributes' => 
  array (
    'quote_identifier' => true,
  ),
  'name' => 'doctrine',
)),);
