<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2020/03/09 10:07:57
sfConfig::add(array(
  'mod_projectscomments_enabled' => true,
  'mod_projectscomments_view_class' => 'sfPHP',
));
