<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2020/03/10 03:15:40
sfConfig::add(array(
  'mod_projectsphases_enabled' => true,
  'mod_projectsphases_view_class' => 'sfPHP',
));
