<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2020/03/09 09:55:36
sfConfig::add(array(
  'mod_versionsstatus_enabled' => true,
  'mod_versionsstatus_view_class' => 'sfPHP',
));
