<?php
// auto-generated by sfSecurityConfigHandler
// date: 2020/03/09 10:07:15
$this->security = array (
  'ldap' => 
  array (
    'is_secure' => false,
  ),
  'restorepassword' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
