<?php
// auto-generated by sfSecurityConfigHandler
// date: 2020/03/09 09:31:17
$this->security = array (
  'ldap' => 
  array (
    'is_secure' => false,
  ),
  'restorepassword' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
