<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2020/03/09 09:55:29
sfConfig::add(array(
  'mod_projectsstatus_enabled' => true,
  'mod_projectsstatus_view_class' => 'sfPHP',
));
